import collector
sp = collector.smartplug('192.168.2.110')
print('test get info:')
print(sp.do('info'))
print()
print('test get cloud info:')
print(sp.do('cloudinfo'))
print()
print('test cloud off:')
print(sp.do('cloudoff'))
print()
print('test switch off:')
print(sp.do('off'))
print()
print('test switch on:')
print(sp.do('on'))
print()
